import type { Listing, Complaint } from './types';

export const DEMO_LISTINGS: Listing[] = [
  {
    id: 'l-001',
    title: 'Yangi pishirilgan non (2 dona)',
    description: 'Bugun tongda tandir non pishirdim, ortib qoldi. Ikkita to\'la non, hali issiq. O\'zim ham qishloqdan keltirgan, kimdir muhtoj bo\'lsa olasin.',
    category: 'food',
    condition: 'new',
    district: 'Chilonzor',
    landmark: 'Chilonzor metrosi yaqinidagi 3-uy',
    images: ['https://images.pexels.com/photos/7965990/pexels-photo-7965990.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'available',
    giverName: 'Dilfuza opa',
    giverId: 'u-001',
    giverRating: 5,
    giverHelpCount: 12,
    giverPhone: '+998 90 123 45 67',
    giverTelegram: '@dilfuza_opa',
    createdAt: '2026-09-12T08:00:00Z',
    adminStatus: 'approved',
    foodDetails: {
      packagedDate: '2026-09-12',
      expiryDate: '2026-09-14',
      isCooked: true,
    },
  },
  {
    id: 'l-002',
    title: 'Qishki kurtka (erkaklar, L razmer)',
    description: 'O\'g\'lim o\'sib ketdi, kurtka kichik bo\'lib qoldi. Holati yaxshi, yamug\'i yo\'q, fermuar ishlaydi. Qishda kimgadir isinib yurish uchun yaxshi.',
    category: 'clothing',
    condition: 'good',
    district: 'Yunusobod',
    landmark: 'Yunusobod 19-mavze, 4-uy oldi',
    images: ['https://images.pexels.com/photos/6516571/pexels-photo-6516571.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'available',
    giverName: 'Rustam',
    giverId: 'u-002',
    giverRating: 4,
    giverHelpCount: 5,
    giverPhone: '+998 91 234 56 78',
    giverTelegram: '@rustam_tash',
    createdAt: '2026-09-11T14:00:00Z',
    adminStatus: 'approved',
  },
  {
    id: 'l-003',
    title: 'Yog\'och stollar (2 dona)',
    description: 'Ko\'chib o\'tish sababli stollar kerak emas. Ikki dona yog\'och stul, baravar ishlaydi. Olib ketuvchi o\'zi kelib olib ketishi kerak.',
    category: 'furniture',
    condition: 'used',
    district: 'Sergeli',
    landmark: 'Sergeli yangi mavze, bozor orqasi',
    images: ['https://images.pexels.com/photos/11591259/pexels-photo-11591259.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'available',
    giverName: 'Malika',
    giverId: 'u-003',
    giverRating: 4,
    giverHelpCount: 3,
    giverPhone: '+998 93 345 67 89',
    giverTelegram: '@malika_sergeli',
    createdAt: '2026-09-10T10:00:00Z',
    adminStatus: 'approved',
  },
  {
    id: 'l-004',
    title: 'Kitoblar to\'plami (15 dona)',
    description: 'Bolalarim katta bo\'lib ketdi, ertak va o\'qish kitoblari ortib qoldi. O\'zbek va rus tilidagi kitoblar. Maktabga boradigan bolaga yaxshi sovg\'a.',
    category: 'books',
    condition: 'good',
    district: 'Olmazor',
    landmark: 'Olmazor metro yaqini, Buyuk Ipak Yo\'li',
    images: ['https://images.pexels.com/photos/18847269/pexels-photo-18847269.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'available',
    giverName: 'Gulnora',
    giverId: 'u-004',
    giverRating: 5,
    giverHelpCount: 8,
    giverPhone: '+998 94 456 78 90',
    giverTelegram: '@gulnora_kitob',
    createdAt: '2026-09-09T12:00:00Z',
    adminStatus: 'approved',
  },
  {
    id: 'l-005',
    title: 'Bolalar o\'yinchoqlari to\'plami',
    description: 'Qizim katta bo\'lgani uchun o\'yinchoqlar kerak emas. O\'yinchoqlar toza va yaxshi holatda. Yumshoq va plastik o\'yinchoqlar bor.',
    category: 'kids',
    condition: 'good',
    district: 'Yashnobod',
    landmark: 'Yashnobod 6-mavze, bolalar bog\'chasi yonida',
    images: ['https://images.pexels.com/photos/11116578/pexels-photo-11116578.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'reserved',
    giverName: 'Nodira',
    giverId: 'u-005',
    giverRating: 5,
    giverHelpCount: 15,
    giverPhone: '+998 95 567 89 01',
    giverTelegram: '@nodira_yash',
    createdAt: '2026-09-08T09:00:00Z',
    adminStatus: 'approved',
    reservedBy: 'u-current',
    reservedAt: '2026-09-13T10:00:00Z',
  },
  {
    id: 'l-006',
    title: 'Acer noutbuki (ishlaydi)',
    description: 'Yangi noutbuk olganim uchun eskisi kerak emas. Windows 10 o\'rnatilgan, 4GB RAM, 500GB disk. Internet va ofis dasturlari uchun yaxshi. Kabel va quvvatlagich bilan.',
    category: 'tech',
    condition: 'used',
    district: 'Mirobod',
    landmark: 'Mirobod ko\'chasi, 14-uy',
    images: ['https://images.pexels.com/photos/26150604/pexels-photo-26150604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'available',
    giverName: 'Sardor',
    giverId: 'u-006',
    giverRating: 4,
    giverHelpCount: 2,
    giverPhone: '+998 97 678 90 12',
    giverTelegram: '@sardor_tech',
    createdAt: '2026-09-07T16:00:00Z',
    adminStatus: 'approved',
  },
  {
    id: 'l-007',
    title: 'Qadoqlangan osh (1 lagan)',
    description: 'Bayramda osh ko\'p pishdi, ortib qoldi. Toza idishda qadoqlangan, hali sovugani yo\'q. Bugun olib ketish kerak.',
    category: 'food',
    condition: 'new',
    district: 'Shayxontohur',
    landmark: 'Shayxontohur, Eski Juva bozor orqasi',
    images: ['https://images.pexels.com/photos/4198362/pexels-photo-4198362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'available',
    giverName: 'Karim aka',
    giverId: 'u-007',
    giverRating: 5,
    giverHelpCount: 20,
    giverPhone: '+998 99 789 01 23',
    giverTelegram: '@karim_aka',
    createdAt: '2026-09-13T07:00:00Z',
    adminStatus: 'approved',
    foodDetails: {
      packagedDate: '2026-09-13',
      expiryDate: '2026-09-13',
      isCooked: true,
    },
  },
  {
    id: 'l-008',
    title: 'Fermuarli kurtka (ayollar, M razmer)',
    description: 'Yangi kurtka, faqat bir marta kiyilgan. Rangi yashil, issiq va qulay. Kimdir sovuqda tekin isinish uchun beraman.',
    category: 'clothing',
    condition: 'new',
    district: 'Yakkasaroy',
    landmark: 'Yakkasaroy, Milliy Bog\' yaqinida',
    images: ['https://images.pexels.com/photos/15473006/pexels-photo-15473006.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'taken',
    giverName: 'Aziza',
    giverId: 'u-008',
    giverRating: 5,
    giverHelpCount: 7,
    giverPhone: '+998 90 890 23 45',
    giverTelegram: '@aziza_yak',
    createdAt: '2026-09-05T11:00:00Z',
    adminStatus: 'approved',
  },
];

export const DEMO_COMPLAINTS: Complaint[] = [
  {
    id: 'c-001',
    listingId: 'l-003',
    listingTitle: 'Yog\'och stollar (2 dona)',
    reason: 'money',
    description: 'Stollarni olib ketgani keldi, lekin pul so\'radi. "Buning hammasi tekin emas" dedi.',
    reporterName: 'Anonim',
    createdAt: '2026-09-11T15:00:00Z',
    status: 'pending',
  },
  {
    id: 'c-002',
    listingId: 'l-006',
    listingTitle: 'Acer noutbuki (ishlaydi)',
    reason: 'false',
    description: 'Noutbukning RAM i 4GB emas, 2GB ekan. Tavsifda noto\'g\'ri yozilgan.',
    reporterName: 'Jasur',
    createdAt: '2026-09-08T18:00:00Z',
    status: 'reviewed',
  },
];

export const DEMO_PENDING_LISTINGS: Listing[] = [
  {
    id: 'l-009',
    title: 'Sovutgich (kichik)',
    description: 'Kichik sovutgich ishlaydi, lekin biroz shovqinli. Yangi sovutgich olganim uchun kerak emas.',
    category: 'tech',
    condition: 'used',
    district: 'Uchtepa',
    landmark: 'Uchtepa 5-mavze',
    images: ['https://images.pexels.com/photos/4065704/pexels-photo-4065704.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    status: 'available',
    giverName: 'Bekzod',
    giverId: 'u-009',
    giverRating: 0,
    giverHelpCount: 0,
    giverPhone: '+998 91 111 22 33',
    giverTelegram: '@bekzod_ucht',
    createdAt: '2026-09-13T06:00:00Z',
    adminStatus: 'pending',
  },
];
